services:
  - type: web
    name: political-violence-backend
    env: python
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /usr/local/share/.cache/ms-playwright
